### ISSUE TITLE
Failed to parse table keyid

### ISSUE THREAD

**Issue by zxy909** [p4tc-dev/iproute2-p4tc-pub#20]
Hi，
There seems something wrong about the code for parsing json, which will cause an error to be returned when delivering runtime entries.

error log
```
root@p4tc:/# tc p4runtime create redirect_srcip/table/ingress/nh_table hdr.ipv4.srcAddr 192.168.236.1 prio 1 action redirect_srcip/ingress/send_nh param port type dev enp0s2 param smac type macaddr b8:ce:f6:4b:68:35 param dmac type macaddr ac:1f:6b:e4:ff:93
Unexpected error type not number <keyid>
Failed to parse table keyid:<keyid> for:
<{
.....
}>
Failed to parse tables
parse keys - Unable to find pipeline redirect_srcip
```
in iproute2-p4tc-pub/tc/p4_tc_json.c, should JSON_TABLE_LIST_TABLE_KEY_ID be JSON_TABLE_LIST_TABLE_KEY_FIELD_ID?
```
	ret = cjson_get_int(table_cjson, JSON_TABLE_LIST_TABLE_KEY_ID, &keyid);
	if (ret) {
		fprintf(stderr, "Failed to parse table keyid:<%s> for:\n<%s>\n",
			JSON_TABLE_LIST_TABLE_KEY_ID,
			cJSON_Print(table_cjson));
		return -1;
	}
```
The error disappeared after replacing.

**Comment by jhsmt** [comment]
@zxy909 Thank you! This is a known issue. 
The "keyid" is obsolete. We have a fix but have been too busy preparing a new release to push it out. I am assuming you are saying you deleted the lines you listed above, which is 95% of the fix. I would have asked you to submit a patch - but we have one already. Your message triggered us to move the patch from our internal tree to github. See:  https://github.com/p4tc-dev/iproute2-p4tc-pub/pull/21
